// Generated by api/scripts/export_voices.py — do not edit by hand.
// Source of truth: api/app/core/articulation.py and api/app/core/kit.py
// Regenerate: docker compose exec -T -e PYTHONPATH=/app api \
//   python scripts/export_voices.py > web/lib/audio/voices.generated.ts

import type { Instrument } from "./types";

/** How an articulation reshapes a note in the browser. */
export interface VoiceSpec {
  /** Envelope and filter, applied to the synth voice. Null for drums. */
  browser: {
    oscillator: string;
    attack: number;
    decay: number;
    sustain: number;
    release: number;
    filter_freq: number;
  } | null;
  velocityScale: number;
  durationScale: number;
  transpose: number;
}

/** Per-instrument voices. The first key of each is that instrument's default. */
export const VOICES: Record<Instrument, Record<string, VoiceSpec>> = {
  "violin": {
    "sustain": {
      "browser": {
        "oscillator": "fmsine",
        "attack": 0.09,
        "decay": 0.2,
        "sustain": 0.85,
        "release": 0.7,
        "filter_freq": 7000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "pizz": {
      "browser": {
        "oscillator": "triangle",
        "attack": 0.002,
        "decay": 0.18,
        "sustain": 0.0,
        "release": 0.25,
        "filter_freq": 5000
      },
      "velocityScale": 1.0,
      "durationScale": 0.35,
      "transpose": 0
    },
    "tremolo": {
      "browser": {
        "oscillator": "sawtooth",
        "attack": 0.05,
        "decay": 0.1,
        "sustain": 0.8,
        "release": 0.4,
        "filter_freq": 6000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "harp": {
      "browser": {
        "oscillator": "triangle",
        "attack": 0.003,
        "decay": 0.6,
        "sustain": 0.1,
        "release": 1.2,
        "filter_freq": 8000
      },
      "velocityScale": 1.0,
      "durationScale": 0.8,
      "transpose": 0
    }
  },
  "flute": {
    "sustain": {
      "browser": {
        "oscillator": "sine",
        "attack": 0.06,
        "decay": 0.1,
        "sustain": 0.9,
        "release": 0.4,
        "filter_freq": 11000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "recorder": {
      "browser": {
        "oscillator": "sine",
        "attack": 0.04,
        "decay": 0.1,
        "sustain": 0.85,
        "release": 0.3,
        "filter_freq": 9000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "pan_flute": {
      "browser": {
        "oscillator": "sine",
        "attack": 0.11,
        "decay": 0.15,
        "sustain": 0.8,
        "release": 0.6,
        "filter_freq": 7000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    }
  },
  "guitar": {
    "clean": {
      "browser": {
        "oscillator": "sawtooth",
        "attack": 0.004,
        "decay": 0.3,
        "sustain": 0.2,
        "release": 0.6,
        "filter_freq": 5000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "nylon": {
      "browser": {
        "oscillator": "triangle",
        "attack": 0.006,
        "decay": 0.35,
        "sustain": 0.15,
        "release": 0.7,
        "filter_freq": 4000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "palm_mute": {
      "browser": {
        "oscillator": "square",
        "attack": 0.002,
        "decay": 0.12,
        "sustain": 0.0,
        "release": 0.15,
        "filter_freq": 1800
      },
      "velocityScale": 1.0,
      "durationScale": 0.4,
      "transpose": 0
    },
    "harmonics": {
      "browser": {
        "oscillator": "sine",
        "attack": 0.005,
        "decay": 0.5,
        "sustain": 0.1,
        "release": 1.0,
        "filter_freq": 9000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 12
    },
    "twelve_string": {
      "browser": {
        "oscillator": "sawtooth",
        "attack": 0.005,
        "decay": 0.4,
        "sustain": 0.25,
        "release": 0.8,
        "filter_freq": 6000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "overdrive": {
      "browser": {
        "oscillator": "sawtooth",
        "attack": 0.003,
        "decay": 0.2,
        "sustain": 0.6,
        "release": 0.5,
        "filter_freq": 3500
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    }
  },
  "keys": {
    "sustain": {
      "browser": {
        "oscillator": "triangle",
        "attack": 0.005,
        "decay": 0.4,
        "sustain": 0.3,
        "release": 1.2,
        "filter_freq": 9000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "rhodes": {
      "browser": {
        "oscillator": "fmsine",
        "attack": 0.01,
        "decay": 0.5,
        "sustain": 0.4,
        "release": 1.4,
        "filter_freq": 6000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "fm_piano": {
      "browser": {
        "oscillator": "fmsine",
        "attack": 0.008,
        "decay": 0.4,
        "sustain": 0.35,
        "release": 1.0,
        "filter_freq": 8000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "harpsichord": {
      "browser": {
        "oscillator": "square",
        "attack": 0.002,
        "decay": 0.25,
        "sustain": 0.0,
        "release": 0.4,
        "filter_freq": 7000
      },
      "velocityScale": 1.0,
      "durationScale": 0.6,
      "transpose": 0
    },
    "bright": {
      "browser": {
        "oscillator": "triangle",
        "attack": 0.004,
        "decay": 0.35,
        "sustain": 0.3,
        "release": 1.0,
        "filter_freq": 11000
      },
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    }
  },
  "drums": {
    "sustain": {
      "browser": null,
      "velocityScale": 1.0,
      "durationScale": 1.0,
      "transpose": 0
    },
    "ghost": {
      "browser": null,
      "velocityScale": 0.3,
      "durationScale": 1.0,
      "transpose": 0
    },
    "accent": {
      "browser": null,
      "velocityScale": 1.25,
      "durationScale": 1.0,
      "transpose": 0
    }
  }
};

/** Shaping articulations any melodic instrument may use. */
export const UNIVERSAL: Record<string, VoiceSpec> = {
  "staccato": {
    "browser": null,
    "velocityScale": 1.0,
    "durationScale": 0.4,
    "transpose": 0
  },
  "accent": {
    "browser": null,
    "velocityScale": 1.25,
    "durationScale": 1.0,
    "transpose": 0
  },
  "ghost": {
    "browser": null,
    "velocityScale": 0.3,
    "durationScale": 1.0,
    "transpose": 0
  }
};

/** Named drum kit pieces: MIDI note and default velocity. */
export const PIECES: Record<string, { note: number; vel: number }> = {
  "kick": {
    "note": 36,
    "vel": 100
  },
  "kick_soft": {
    "note": 35,
    "vel": 70
  },
  "snare": {
    "note": 38,
    "vel": 95
  },
  "snare_rim": {
    "note": 37,
    "vel": 70
  },
  "ghost_snare": {
    "note": 38,
    "vel": 28
  },
  "snare_roll": {
    "note": 40,
    "vel": 60
  },
  "hat_closed": {
    "note": 42,
    "vel": 70
  },
  "hat_pedal": {
    "note": 44,
    "vel": 55
  },
  "hat_open": {
    "note": 46,
    "vel": 80
  },
  "ride": {
    "note": 51,
    "vel": 70
  },
  "ride_bell": {
    "note": 53,
    "vel": 85
  },
  "crash": {
    "note": 49,
    "vel": 100
  },
  "splash": {
    "note": 55,
    "vel": 75
  },
  "china": {
    "note": 52,
    "vel": 95
  },
  "tom_hi": {
    "note": 50,
    "vel": 85
  },
  "tom_mid": {
    "note": 47,
    "vel": 85
  },
  "tom_lo": {
    "note": 43,
    "vel": 85
  },
  "tom_floor": {
    "note": 41,
    "vel": 85
  },
  "cowbell": {
    "note": 56,
    "vel": 80
  },
  "tambourine": {
    "note": 54,
    "vel": 70
  },
  "shaker": {
    "note": 70,
    "vel": 60
  },
  "clap": {
    "note": 39,
    "vel": 85
  },
  "sticks": {
    "note": 31,
    "vel": 60
  }
};

/** The voice a note should play with, falling back to the instrument's default. */
export function voiceFor(instrument: Instrument, articulation?: string | null): VoiceSpec {
  const own = VOICES[instrument];
  const fallback = Object.values(own)[0];
  if (!articulation) return fallback;

  const wanted = articulation.trim().toLowerCase();
  if (own[wanted]) return own[wanted];

  const shaping = UNIVERSAL[wanted];
  // A shaping articulation keeps the instrument's timbre and only reshapes it.
  return shaping ? { ...shaping, browser: fallback.browser } : fallback;
}
