"""Generate the frontend's articulation table from the Python source.

The registry in app/core/articulation.py is the single definition; this
writes web/lib/audio/voices.generated.ts so the browser and the MIDI
exporter can never drift apart.

    docker compose exec -T -e PYTHONPATH=/app api python scripts/export_voices.py \
        > web/lib/audio/voices.generated.ts
"""

import json

from app.core.articulation import UNIVERSAL, VOICES
from app.core.kit import BY_NAME

HEADER = """// Generated by api/scripts/export_voices.py — do not edit by hand.
// Source of truth: api/app/core/articulation.py and api/app/core/kit.py
// Regenerate: docker compose exec -T -e PYTHONPATH=/app api \\
//   python scripts/export_voices.py > web/lib/audio/voices.generated.ts

import type { Instrument } from "./types";

/** How an articulation reshapes a note in the browser. */
export interface VoiceSpec {
  /** Envelope and filter, applied to the synth voice. Null for drums. */
  browser: {
    oscillator: string;
    attack: number;
    decay: number;
    sustain: number;
    release: number;
    filter_freq: number;
  } | null;
  velocityScale: number;
  durationScale: number;
  transpose: number;
}
"""


def main() -> None:
    voices = {
        instrument.value: {
            voice.articulation.value: {
                "browser": voice.browser,
                "velocityScale": voice.velocity_scale,
                "durationScale": voice.duration_scale,
                "transpose": voice.transpose,
            }
            for voice in instrument_voices
        }
        for instrument, instrument_voices in VOICES.items()
    }
    universal = {
        voice.articulation.value: {
            "browser": None,
            "velocityScale": voice.velocity_scale,
            "durationScale": voice.duration_scale,
            "transpose": 0,
        }
        for voice in UNIVERSAL
    }
    pieces = {name: {"note": p.note, "vel": p.velocity} for name, p in BY_NAME.items()}

    print(HEADER)
    print("/** Per-instrument voices. The first key of each is that instrument's default. */")
    print(
        "export const VOICES: Record<Instrument, Record<string, VoiceSpec>> ="
        f" {json.dumps(voices, indent=2)};\n"
    )
    print("/** Shaping articulations any melodic instrument may use. */")
    print(f"export const UNIVERSAL: Record<string, VoiceSpec> = {json.dumps(universal, indent=2)};\n")
    print("/** Named drum kit pieces: MIDI note and default velocity. */")
    print(
        "export const PIECES: Record<string, { note: number; vel: number }> ="
        f" {json.dumps(pieces, indent=2)};\n"
    )
    print("""/** The voice a note should play with, falling back to the instrument's default. */
export function voiceFor(instrument: Instrument, articulation?: string | null): VoiceSpec {
  const own = VOICES[instrument];
  const fallback = Object.values(own)[0];
  if (!articulation) return fallback;

  const wanted = articulation.trim().toLowerCase();
  if (own[wanted]) return own[wanted];

  const shaping = UNIVERSAL[wanted];
  // A shaping articulation keeps the instrument's timbre and only reshapes it.
  return shaping ? { ...shaping, browser: fallback.browser } : fallback;
}""")


if __name__ == "__main__":
    main()
